apiVersion: apps/v1
kind: Deployment
metadata:
  name: gda-java
spec:
  replicas: 3
  selector:
    matchLabels:
      name: gda-java
  template:
    metadata:
      labels:
        name: gda-java
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: backend
        image: <IMAGE_BACKEND>:<VERSION>
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /hello
            port: http
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /hello
            port: http
          failureThreshold: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 4000Mi
          limits:
            cpu: 100m
            memory: 700Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          procMount: "Default"
